+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Dec  3 12:55:00 2022 - INFO  - Start to run test.
+ openssl dsaparam -noout -out dsakey.pem -genkey 2048
oe_test_openssl_file_signature_verification.sh: line 23: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 24'
+ message='oe_test_openssl_file_signature_verification.sh line 24'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 24'
Sat Dec  3 12:55:01 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 24
+ return 0
+ grep 'BEGIN DSA PRIVATE KEY' dsakey.pem
grep: dsakey.pem: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 26'
+ message='oe_test_openssl_file_signature_verification.sh line 26'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 26'
Sat Dec  3 12:55:02 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 26
+ return 0
+ echo 'It is a test'
+ openssl dgst -sha1 -sign dsakey.pem -out dsasign.bin file.txt
oe_test_openssl_file_signature_verification.sh: line 28: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 29'
+ message='oe_test_openssl_file_signature_verification.sh line 29'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 29'
Sat Dec  3 12:55:02 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 29
+ return 0
+ test -f dsasign.bin
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 31'
+ message='oe_test_openssl_file_signature_verification.sh line 31'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 31'
Sat Dec  3 12:55:03 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 31
+ return 0
+ openssl dgst -sha1 -prverify dsakey.pem -signature dsasign.bin file.txt
+ grep 'Verified OK'
oe_test_openssl_file_signature_verification.sh: line 32: openssl: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 33'
+ message='oe_test_openssl_file_signature_verification.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 33'
Sat Dec  3 12:55:04 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 33
+ return 0
+ openssl genrsa -out rsakey.pem
oe_test_openssl_file_signature_verification.sh: line 34: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 35'
+ message='oe_test_openssl_file_signature_verification.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 35'
Sat Dec  3 12:55:05 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 35
+ return 0
+ grep 'BEGIN RSA PRIVATE KEY' rsakey.pem
grep: rsakey.pem: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 37'
+ message='oe_test_openssl_file_signature_verification.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 37'
Sat Dec  3 12:55:06 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 37
+ return 0
+ openssl rsa -in rsakey.pem -pubout -out rsakey-pub.pem
oe_test_openssl_file_signature_verification.sh: line 38: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 39'
+ message='oe_test_openssl_file_signature_verification.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 39'
Sat Dec  3 12:55:06 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 39
+ return 0
+ grep 'BEGIN PUBLIC KEY' rsakey-pub.pem
grep: rsakey-pub.pem: No such file or directory
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 41'
+ message='oe_test_openssl_file_signature_verification.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 41'
Sat Dec  3 12:55:07 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 41
+ return 0
+ openssl sha1 -sign rsakey.pem -out rsasign.bin file.txt
oe_test_openssl_file_signature_verification.sh: line 42: openssl: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 43'
+ message='oe_test_openssl_file_signature_verification.sh line 43'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 43'
Sat Dec  3 12:55:08 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 43
+ return 0
+ test -f rsasign.bin
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 45'
+ message='oe_test_openssl_file_signature_verification.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 45'
Sat Dec  3 12:55:09 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 45
+ return 0
+ openssl sha1 -verify rsakey-pub.pem -signature rsasign.bin file.txt
+ grep 'Verified OK'
oe_test_openssl_file_signature_verification.sh: line 46: openssl: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_file_signature_verification.sh line 47'
+ message='oe_test_openssl_file_signature_verification.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_file_signature_verification.sh line 47'
Sat Dec  3 12:55:10 2022 - ERROR - oe_test_openssl_file_signature_verification.sh line 47
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Dec  3 12:55:10 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 12
+ test 12 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Dec  3 12:55:11 2022 - ERROR - failed to execute the case.
+ exit 12
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Dec  3 12:55:12 2022 - INFO  - Start to restore the test environment.
++ ls
++ grep -v '\.sh\|common'
+ rm -f file.txt
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Dec  3 12:55:13 2022 - INFO  - End to restore the test environment.
