+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Mon Dec  5 02:01:57 2022 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL rust
+ pkgs=rust
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs rust --node 1 --tempfile ''
+ tmpfile2='Last metadata expiration check: 0:05:20 ago on Mon 05 Dec 2022 01:57:11 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides libLLVM-13.so.2()(64bit) needed by rust-1.58.1-1.an8.riscv64
  - nothing provides libLLVM-13.so.2(LLVM_13)(64bit) needed by rust-1.58.1-1.an8.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages)'
+ '[' -z '' ']'
+ tmpfile='Last metadata expiration check: 0:05:20 ago on Mon 05 Dec 2022 01:57:11 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides libLLVM-13.so.2()(64bit) needed by rust-1.58.1-1.an8.riscv64
  - nothing provides libLLVM-13.so.2(LLVM_13)(64bit) needed by rust-1.58.1-1.an8.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages)'
+ cp ../common/hello.rs ../common/lib.rs ../common/main.rs ../common/myhello.rs ../common/pub.rs ../common/test.rs ../common/war.rs ./
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Mon Dec  5 02:02:35 2022 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Mon Dec  5 02:02:35 2022 - INFO  - Start to run test.
+ rustdoc -h
+ grep Options
oe_test_rustdoc.sh: line 31: rustdoc: command not found
+ CHECK_RESULT 1 0 0 'Help information printing failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Help information printing failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Help information printing failed'
+ LOG_ERROR 'Help information printing failed'
+ message='Help information printing failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Help information printing failed'
Mon Dec  5 02:02:37 2022 - ERROR - Help information printing failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 32'
+ message='oe_test_rustdoc.sh line 32'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 32'
Mon Dec  5 02:02:38 2022 - ERROR - oe_test_rustdoc.sh line 32
+ return 0
+ rustdoc -V
+ grep -E '[0-9]'
oe_test_rustdoc.sh: line 33: rustdoc: command not found
+ CHECK_RESULT 1 0 0 'Failed to output the version information'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to output the version information'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to output the version information'
+ LOG_ERROR 'Failed to output the version information'
+ message='Failed to output the version information'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to output the version information'
Mon Dec  5 02:02:39 2022 - ERROR - Failed to output the version information
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 34'
+ message='oe_test_rustdoc.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 34'
Mon Dec  5 02:02:40 2022 - ERROR - oe_test_rustdoc.sh line 34
+ return 0
+ rustdoc -v -V
+ grep -E 'release|version|[0-9]'
oe_test_rustdoc.sh: line 35: rustdoc: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 36'
+ message='oe_test_rustdoc.sh line 36'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 36'
Mon Dec  5 02:02:41 2022 - ERROR - oe_test_rustdoc.sh line 36
+ return 0
+ rustdoc test.rs -o doc --crate-name mycrate
oe_test_rustdoc.sh: line 37: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 38'
+ message='oe_test_rustdoc.sh line 38'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 38'
Mon Dec  5 02:02:42 2022 - ERROR - oe_test_rustdoc.sh line 38
+ return 0
+ test -d doc/mycrate
+ CHECK_RESULT 1 0 0 'Failed to specify the output path'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to specify the output path'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to specify the output path'
+ LOG_ERROR 'Failed to specify the output path'
+ message='Failed to specify the output path'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to specify the output path'
Mon Dec  5 02:02:43 2022 - ERROR - Failed to specify the output path
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 40'
+ message='oe_test_rustdoc.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 40'
Mon Dec  5 02:02:43 2022 - ERROR - oe_test_rustdoc.sh line 40
+ return 0
+ rustdoc test.rs -L doc/
oe_test_rustdoc.sh: line 41: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 42'
+ message='oe_test_rustdoc.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 42'
Mon Dec  5 02:02:44 2022 - ERROR - oe_test_rustdoc.sh line 42
+ return 0
+ rustdoc hello.rs --cfg hello
oe_test_rustdoc.sh: line 43: rustdoc: command not found
+ test -d doc/hello
+ CHECK_RESULT 1 0 0 'Failed to pass configuration parameters'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to pass configuration parameters'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to pass configuration parameters'
+ LOG_ERROR 'Failed to pass configuration parameters'
+ message='Failed to pass configuration parameters'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to pass configuration parameters'
Mon Dec  5 02:02:45 2022 - ERROR - Failed to pass configuration parameters
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 45'
+ message='oe_test_rustdoc.sh line 45'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 45'
Mon Dec  5 02:02:46 2022 - ERROR - oe_test_rustdoc.sh line 45
+ return 0
+ rustdoc test.rs --extern doc/
oe_test_rustdoc.sh: line 46: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 47'
+ message='oe_test_rustdoc.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 47'
Mon Dec  5 02:02:47 2022 - ERROR - oe_test_rustdoc.sh line 47
+ return 0
+ rustdoc test.rs -C target_feature=+avx
oe_test_rustdoc.sh: line 48: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 49'
+ message='oe_test_rustdoc.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 49'
Mon Dec  5 02:02:48 2022 - ERROR - oe_test_rustdoc.sh line 49
+ return 0
+ rustdoc --document-private-items test.rs
oe_test_rustdoc.sh: line 50: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 51'
+ message='oe_test_rustdoc.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 51'
Mon Dec  5 02:02:49 2022 - ERROR - oe_test_rustdoc.sh line 51
+ return 0
+ rustdoc test.rs --test
+ grep -E 'running|tests'
oe_test_rustdoc.sh: line 52: rustdoc: command not found
+ CHECK_RESULT 1 0 0 'Failed to run the test code'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to run the test code'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to run the test code'
+ LOG_ERROR 'Failed to run the test code'
+ message='Failed to run the test code'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to run the test code'
Mon Dec  5 02:02:50 2022 - ERROR - Failed to run the test code
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 53'
+ message='oe_test_rustdoc.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 53'
Mon Dec  5 02:02:51 2022 - ERROR - oe_test_rustdoc.sh line 53
+ return 0
+ rustdoc test.rs --html-in-header doc/hello/all.html
oe_test_rustdoc.sh: line 54: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 55'
+ message='oe_test_rustdoc.sh line 55'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 55'
Mon Dec  5 02:02:52 2022 - ERROR - oe_test_rustdoc.sh line 55
+ return 0
+ rustdoc test.rs --html-after-content doc/hello/all.html
oe_test_rustdoc.sh: line 56: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 57'
+ message='oe_test_rustdoc.sh line 57'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 57'
Mon Dec  5 02:02:53 2022 - ERROR - oe_test_rustdoc.sh line 57
+ return 0
+ rustdoc test.rs --html-after-content doc/hello/all.html
oe_test_rustdoc.sh: line 58: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 59'
+ message='oe_test_rustdoc.sh line 59'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 59'
Mon Dec  5 02:02:54 2022 - ERROR - oe_test_rustdoc.sh line 59
+ return 0
+ rustdoc test.rs --markdown-no-toc
oe_test_rustdoc.sh: line 60: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 61'
+ message='oe_test_rustdoc.sh line 61'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 61'
Mon Dec  5 02:02:55 2022 - ERROR - oe_test_rustdoc.sh line 61
+ return 0
+ rustdoc test.rs -e doc/dark.css
oe_test_rustdoc.sh: line 62: rustdoc: command not found
+ CHECK_RESULT 127
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 63'
+ message='oe_test_rustdoc.sh line 63'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 63'
Mon Dec  5 02:02:55 2022 - ERROR - oe_test_rustdoc.sh line 63
+ return 0
+ rustdoc lib.rs --crate-type=lib -W missing-docs
+ grep warning
+ CHECK_RESULT 1 0 0 'Failed to set Linter option Warn'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to set Linter option Warn'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to set Linter option Warn'
+ LOG_ERROR 'Failed to set Linter option Warn'
+ message='Failed to set Linter option Warn'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to set Linter option Warn'
Mon Dec  5 02:02:56 2022 - ERROR - Failed to set Linter option Warn
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 65'
+ message='oe_test_rustdoc.sh line 65'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 65'
Mon Dec  5 02:02:57 2022 - ERROR - oe_test_rustdoc.sh line 65
+ return 0
+ rustdoc lib.rs --crate-type=lib -A missing-docs -o hello_A
oe_test_rustdoc.sh: line 66: rustdoc: command not found
+ test -d hello_A
+ CHECK_RESULT 1 0 0 'Failed to set Linter option Allow'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to set Linter option Allow'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to set Linter option Allow'
+ LOG_ERROR 'Failed to set Linter option Allow'
+ message='Failed to set Linter option Allow'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to set Linter option Allow'
Mon Dec  5 02:02:58 2022 - ERROR - Failed to set Linter option Allow
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 68'
+ message='oe_test_rustdoc.sh line 68'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 68'
Mon Dec  5 02:02:59 2022 - ERROR - oe_test_rustdoc.sh line 68
+ return 0
+ rustdoc lib.rs --crate-type=lib -D missing-docs
+ grep error
+ CHECK_RESULT 1 0 0 'Failed to set Linter option Deny'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to set Linter option Deny'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to set Linter option Deny'
+ LOG_ERROR 'Failed to set Linter option Deny'
+ message='Failed to set Linter option Deny'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to set Linter option Deny'
Mon Dec  5 02:03:00 2022 - ERROR - Failed to set Linter option Deny
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 70'
+ message='oe_test_rustdoc.sh line 70'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 70'
Mon Dec  5 02:03:01 2022 - ERROR - oe_test_rustdoc.sh line 70
+ return 0
+ rustdoc lib.rs --crate-type=lib -F missing-docs
+ grep error
+ CHECK_RESULT 1 0 0 'Failed to set Linter option Forbit'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed to set Linter option Forbit'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed to set Linter option Forbit'
+ LOG_ERROR 'Failed to set Linter option Forbit'
+ message='Failed to set Linter option Forbit'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to set Linter option Forbit'
Mon Dec  5 02:03:02 2022 - ERROR - Failed to set Linter option Forbit
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 72'
+ message='oe_test_rustdoc.sh line 72'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 72'
Mon Dec  5 02:03:02 2022 - ERROR - oe_test_rustdoc.sh line 72
+ return 0
+ rustdoc war.rs --cap-lints warn
oe_test_rustdoc.sh: line 73: rustdoc: command not found
+ CHECK_RESULT 127 0 0 'Failed to set Linter level warning'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Failed to set Linter level warning'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Failed to set Linter level warning'
+ LOG_ERROR 'Failed to set Linter level warning'
+ message='Failed to set Linter level warning'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed to set Linter level warning'
Mon Dec  5 02:03:03 2022 - ERROR - Failed to set Linter level warning
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_rustdoc.sh line 74'
+ message='oe_test_rustdoc.sh line 74'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_rustdoc.sh line 74'
Mon Dec  5 02:03:04 2022 - ERROR - oe_test_rustdoc.sh line 74
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Mon Dec  5 02:03:05 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 21
+ test 21 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Mon Dec  5 02:03:06 2022 - ERROR - failed to execute the case.
+ exit 21
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Mon Dec  5 02:03:07 2022 - INFO  - start environment cleanup.
+ rm -rf ./hello.rs ./lib.rs ./main.rs ./myhello.rs ./pub.rs ./test.rs ./war.rs 'doc*' hello.rs
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z Last metadata expiration check: 0:05:20 ago on Mon 05 Dec 2022 01:57:11 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides libLLVM-13.so.2()(64bit) needed by rust-1.58.1-1.an8.riscv64
  - nothing provides libLLVM-13.so.2(LLVM_13)(64bit) needed by rust-1.58.1-1.an8.riscv64
(try to add '--skip-broken' to skip uninstallable packages) ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile 'Last metadata expiration check: 0:05:20 ago on Mon 05 Dec 2022 01:57:11 AM EST.
Error: 
 Problem: conflicting requests
  - nothing provides libLLVM-13.so.2()(64bit) needed by rust-1.58.1-1.an8.riscv64
  - nothing provides libLLVM-13.so.2(LLVM_13)(64bit) needed by rust-1.58.1-1.an8.riscv64
(try to add '\''--skip-broken'\'' to skip uninstallable packages)'
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 152, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:05:20 ago on Mon 05 Dec 2022 01:57:11 AM EST.\nError: \n Problem: conflicting requests\n  - nothing provides libLLVM-13.so.2()(64bit) needed by rust-1.58.1-1.an8.riscv64\n  - nothing provides libLLVM-13.so.2(LLVM_13)(64bit) needed by rust-1.58.1-1.an8.riscv64\n(try to add '--skip-broken' to skip uninstallable packages)"
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Mon Dec  5 02:03:10 2022 - INFO  - Finish environment cleanup!
