Thu Dec 29 22:31:07 2022 - INFO  - Start environmental preparation.
Thu Dec 29 22:35:16 2022 - INFO  - End of environmental preparation!
Thu Dec 29 22:35:18 2022 - INFO  - Start to run testcase.
cobblerd does not appear to be running/accessible: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 852, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.9/site-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.9/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 503 Service Unavailable>
Thu Dec 29 22:35:32 2022 - ERROR - Failed option: aclsetup
Thu Dec 29 22:35:34 2022 - ERROR - oe_test_cobbler_other.sh line 34
task started: 2022-12-29_223546_buildiso
running python triggers from /var/lib/cobbler/triggers/task/buildiso/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/buildiso/pre/*
using/creating buildisodir: /var/cache/cobbler/buildiso
  File "/usr/lib/python3.9/site-packages/cobbler/actions/buildiso.py", line 731, in run
Thu Dec 29 22:35:50 2022 - ERROR - Failed option: buildiso
Thu Dec 29 22:35:52 2022 - ERROR - oe_test_cobbler_other.sh line 38
task started: 2022-12-29_223602_import
task started (id=Media import, time=Thu Dec 29 22:36:02 2022)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
distros:
distros:
task started: 2022-12-29_223636_reposync
running python triggers from /var/lib/cobbler/triggers/task/reposync/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/reposync/pre/*
hello, reposync
run, reposync, run!
task started: 2022-12-29_223648_sync
running python triggers from /var/lib/cobbler/triggers/task/sync/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/sync/pre/*
running pre-sync triggers
running: ['rsync', '-rpt', '--copy-links', '--exclude=.cobbler_postun_cleanup', '/var/lib/cobbler/loaders/', '/var/lib/tftpboot']
running: ['rsync', '-rpt', '--copy-links', '--exclude=README.grubconfig', '/var/lib/cobbler/grub_config/', '/var/lib/tftpboot']
running post-sync triggers
running python triggers from /var/lib/cobbler/triggers/sync/post/*
running python trigger cobbler.modules.sync_post_restart_services
running shell triggers from /var/lib/cobbler/triggers/sync/post/*
task started: 2022-12-29_223704_validate_autoinstall_files
running python triggers from /var/lib/cobbler/triggers/task/validate_autoinstall_files/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/validate_autoinstall_files/pre/*
Cobbler 3.2.0
Successfully got file from https://cobbler.github.io/signatures/3.0.x/latest.json
Signatures were successfully loaded
Currently loaded signatures:
11 breeds with 124 total signatures loaded
task started: 2022-12-29_223808_get_loaders
running python triggers from /var/lib/cobbler/triggers/task/get_loaders/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/get_loaders/pre/*
task started: 2022-12-29_223835_hardlink
running python triggers from /var/lib/cobbler/triggers/task/hardlink/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/hardlink/pre/*
now hardlinking to save space, this may take some time.
running: /usr/bin/hardlink -c -v /var/www/cobbler/distro_mirror /var/www/cobbler/repo_mirror
running: /usr/bin/hardlink -c -v /var/www/cobbler/distro_mirror /var/www/cobbler/repo_mirror
task started: 2022-12-29_223850_replicate
running python triggers from /var/lib/cobbler/triggers/task/replicate/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/replicate/pre/*
Thu Dec 29 22:38:57 2022 - INFO  - End to run testcase.
Thu Dec 29 22:38:59 2022 - ERROR - failed to execute the case.
Thu Dec 29 22:39:00 2022 - INFO  - Start to restore the test environment.
Thu Dec 29 22:40:44 2022 - INFO  - End to restore the test environment.
