+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Dec  3 13:23:58 2022 - INFO  - Start to run test.
+ cat
+ expect
spawn openssl enc -aes-256-cbc -salt -in test.txt -out test.enc
couldn't execute "openssl": no such file or directory
    while executing
"spawn openssl enc -aes-256-cbc -salt -in test.txt -out test.enc"
+ grep better testlog1
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 39'
+ message='oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 39'
Sat Dec  3 13:23:59 2022 - ERROR - oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 39
+ return 0
+ test -f test.enc
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 41'
+ message='oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 41'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 41'
Sat Dec  3 13:24:00 2022 - ERROR - oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 41
+ return 0
+ expect
spawn openssl enc -d -aes-256-cbc -in test.enc
couldn't execute "openssl": no such file or directory
    while executing
"spawn openssl enc -d -aes-256-cbc -in test.enc"
+ grep 'Byebye!' testlog2
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 51'
+ message='oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 51'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 51'
Sat Dec  3 13:24:01 2022 - ERROR - oe_test_openssl_symmetrically_encrypts_decrypts_files.sh line 51
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Dec  3 13:24:02 2022 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Dec  3 13:24:03 2022 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Dec  3 13:24:04 2022 - INFO  - Start to restore the test environment.
+ rm -f test.txt test.enc testlog1 testlog2
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Dec  3 13:24:04 2022 - INFO  - End to restore the test environment.
